export const CANON_POETS = [
  "William Shakespeare",
  "John Keats",
  "Percy Bysshe Shelley",
  "William Wordsworth",
  "William Blake",
  "Samuel Taylor Coleridge",
  "Lord Byron",
  "Emily Dickinson",
  "Walt Whitman",
  "Robert Frost",
  "William Butler Yeats",
  "T. S. Eliot",
  "Gerard Manley Hopkins",
  "Edgar Allan Poe",
  "Christina Rossetti",
  "Edna St. Vincent Millay",
  "Langston Hughes",
  "Sara Teasdale",
  "A. E. Housman",
  "Robert Browning",
  "Elizabeth Barrett Browning",
  "Alfred Lord Tennyson",
  "Matthew Arnold",
  "John Donne",
  "George Herbert",
  "Andrew Marvell",
  "Anne Bradstreet",
  "Phillis Wheatley",
  "Henry David Thoreau",
  "Ralph Waldo Emerson",
  "Stephen Crane",
  "Carl Sandburg",
  "Wilfred Owen",
  "Siegfried Sassoon",
  "Rupert Brooke",
  "William Carlos Williams",
  "Marianne Moore",
  "Hilda Doolittle",
  "Ezra Pound",
  "John Milton",
  "Geoffrey Chaucer",
  "Edmund Spenser",
  "Sir Philip Sidney",
  "Ben Jonson",
  "Robert Herrick",
  "Henry Vaughan",
  "Thomas Gray",
  "William Cowper",
  "Robert Burns",
  "John Clare",
  "Algernon Charles Swinburne",
  "Dante Gabriel Rossetti",
  "Thomas Hardy",
  "Rudyard Kipling",
  "Robert Louis Stevenson",
  "Henry Wadsworth Longfellow",
  "John Greenleaf Whittier",
  "James Russell Lowell",
  "Oliver Wendell Holmes",
  "Paul Laurence Dunbar",
  "Claude McKay",
  "Countee Cullen",
  "Jean Toomer",
] as const;
